# Generated by Django 4.1.5 on 2023-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_templatelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatelist',
            name='type',
            field=models.CharField(choices=[('single', 'single'), ('multi', 'multi')], default='single', max_length=100),
        ),
    ]
