# Generated by Django 4.1.5 on 2023-01-19 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_templatelist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('seenTime', models.DateTimeField(blank=True, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.contact')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.templatelist')),
            ],
        ),
    ]
