# Generated by Django 4.1.5 on 2023-01-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_templatereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatereport',
            name='msg_id',
            field=models.CharField(default='uhdwihdw', max_length=100),
            preserve_default=False,
        ),
    ]
