# Generated by Django 4.1.5 on 2023-01-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_templatereport_msg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('contact', models.CharField(max_length=100)),
                ('msg_id', models.CharField(max_length=100)),
            ],
        ),
    ]
