# Generated by Django 4.1.5 on 2023-01-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default='ddfds', max_length=100),
            preserve_default=False,
        ),
    ]
